server:
  port: 6000
spring:
  application:
    name: dong-crowd-order
  redis:
    host: localhost
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
paypal:
  mode: sandbox
  clientId: AZDIxxxCmXmG
  clientSecret: EGXxxxl35u
#hystrix timeout
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled:
            true isolation:
              thread:
                timeoutInMilliseconds: 300000
#ribbon timeout
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000